### ISSUE TITLE
Return same url.URL struct instead of string

### ISSUE THREAD

**Issue by Xeoncross** [PuerkitoBio/purell#18]
Why does the [NormalizeURL()](https://github.com/PuerkitoBio/purell/blob/master/purell.go#L171) function take a url.URL but return a string? There are already functions for dealing with string URL's.

**Comment by PuerkitoBio** [comment]
Hello David,

Typically this is passed to `http.Get` or `http.NewRequest`, and the `url.URL` is a pointer, so the URL you passed in is modified and normalized in-place, no need to return it. If you need the `url.URL`, you can just use the one you passed in. (There's a minor caveat to this regarding the `urlesc` package which doesn't escape in-place)

Martin

**Comment by Xeoncross** [comment]
So since the [urlesc.Escape()](https://github.com/PuerkitoBio/urlesc/blob/master/urlesc.go#L147) method simply returns a string, then if I don't pass the result of `NormalizeURL()` back to url.Parse() then I'll lose some of the proper escaping done by `urlesc` and possibly end up with a less-than-normalized URL.

**Comment by PuerkitoBio** [comment]
Recent versions of Go properly escape, so that call to `urlesc` should not be necessary now. So your url.URL would be ok (see #14 that I haven't had time to address yet).
