### ISSUE TITLE
Tests fail with Go1.12rc1

### ISSUE THREAD

**Issue by ianlancetaylor** [PuerkitoBio/purell#28]
When I run `go get github.com/PuerkitoBio/purell` with Go1.12rc1, I get the following.  I think this is due to the fix for https://golang.org/issue/22907.

```
--- FAIL: TestEncodeNecessaryEscapesAll (0.00s)
    purell_test.go:768: Got error parse http://host/
        

 !": net/url: invalid control character in URL
FAIL
FAIL	github.com/PuerkitoBio/purell	0.088s
```

**Comment by mna** [comment]
Thanks for reporting, I'll try to give it a look this weekend! Also, thank you so much for your great work on Go, much appreciated.
