### ISSUE TITLE
FlagRemoveUnnecessaryHostDots doesn't remove extra dots between parts

### ISSUE THREAD

**Issue by michael-peterson-cisco** [PuerkitoBio/purell#36]
It seems like FlagRemoveUnnecessaryHostDots only removes extra leading and trailing dots in the hostname part of the URL. For instance a URL like "http://host..com" doesn't get the extra dots removed.

**Comment by michael-peterson-cisco** [comment]
Just looked at the code and saw this comment:

// Trim the leading and trailing dots

So I guess that's the expectation given that comment.

**Comment by JohnTitor** [comment]
I think that's a failure to check, adding a support for it would be welcome.

**Comment by michael-peterson-cisco** [comment]
Ran into this again...I'll be posting a PR with my fix, but I've never posted a PR to GitHub, so hopefully I'm doing it correctly.

**Comment by michael-peterson-cisco** [comment]
I posted a PR for this issue, but seems like this project isn't getting much love anymore. :(

**Comment by JohnTitor** [comment]
Ah. sorry, I've been busy lately. I'll take a look this weekend!
