### ISSUE TITLE
Reserved characters should not be percent-encoded

### ISSUE THREAD

**Issue by opennota** [PuerkitoBio/purell#7]
purell should not normalize reserved characters, as per [RFC3986](http://tools.ietf.org/html/rfc3986#section-2.2):

      reserved    = gen-delims / sub-delims

      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"

      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="

``` go
package main

import (
	"fmt"

	"github.com/PuerkitoBio/purell"
)

func main() {
	fmt.Println(purell.MustNormalizeURLString("my_(url)", purell.FlagsSafe))
}
```
The above code outputs `my_%28url%29`, whereas it should be `my_(url)`. This is due to a bug in Go stdlib ([issue 5684](https://github.com/golang/go/issues/5684)).

**Comment by PuerkitoBio** [comment]
Totally agree, but as you mention, this is due to the parsing and escaping done by Go's stdlib. Once/if the bug is fixed in Go, this will be fixed too. Not a purell bug per se.

**Comment by opennota** [comment]
I believe that purell should provide its own implementation of Parse.

**Comment by PuerkitoBio** [comment]
Pull requests welcome.
